version: "3"

services:

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    volumes:
      - ./src:/home/node/app/src
      - ./prisma:/home/node/app/prisma
      - ./package.json:/home/node/app/package.json
      - ./pnpm-lock.yaml:/home/node/app/pnpm-lock.yaml
    env_file:
      - ./.env
    command: ["sh", "-c", "pnpm prisma migrate deploy && pnpm start"]
    depends_on:
      database:
        condition: service_healthy
    restart: always

  database:

    container_name: postgres
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  postgres_data: